---
- name: USER PASSWORD CHANGE
  hosts: all
  become: true
  gather_facts: false
  strategy: free

  tasks:
    - name: CHANGE PASSWORD FOR USER
      user:
        name: "{{ user_name }}"
        password: "{{ new_password }}"
